title: Grav
author:
  name: Joe Bloggs
  email: 'joe@example.com'
metadata:
    description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
footer:
  copyright: |
    [Digital Library Technology Services](https://wp.nyu.edu/library-dlts/?target=_blank) and [Accessibility](https://www.nyu.edu/footer/accessibility.html?target=_blank)

  privacy: |  
    Unless otherwise noted, all content copyright **New York University**. All rights reserved.


